### PR TITLE
Fix crash when setting keybind

### LINKED ISSUE #82: Key still in use after exit
i used xclicker with the default hotkey of "f8"

and after i closed it i am no longer able to use the f8 key

everytime i press f8 the current window lose the focus while i press f8, no other window has the focus and when i release the f8 key everythink is normal again ... until i use f8 again

this behavior still remains after restart, even i dont run xclicker again after the boot process

i am using Kubuntu 22.04 LTS without wayland (just the good old X-server)

### LINKED ISSUE #83: Crash when setting the hotkey
When i opened my xclicker today, it crashed whenever i tried to set the hotkeys, after some debugging i noticed it was happening because **g_idle_add** expects a function that returns a boolean, and removes the function from the event list if it returns false, instead, it was receiving a void function, which would cause it to run indefinitely, causing a segmentation fault.

It can be fixed by replacing **g_idle_add** with **g_idle_add_once**.

Im not sure why it suddenly started happening, maybe a GLib update changed the behavior of g_idle_add?

### PR DESCRIPTION
**Pull request by robiot**
Closes #83
possibly also closes #82, #68
I am not on a linux system rn so I cant test but I will try to remember to check when I can.

### CODE REVIEW

**Comment by robiot** [comment]
Yup this seems to have fixed the issue, at least for me. @UrsoTriangularo or @Shringe, could you test if it works on your machine, then I can merge and release?

**Comment by Shringe** [comment]
I can test later today and verify.

**Comment by Shringe** [comment]
@robiot how do I build the nightly with this commit? I have cloned the fix/g_idle_add_once branch and ran `make release`, but the following executable in `./build/release/src/xclicker` still crashes when setting hotkey. I assume that was the stable branch and there is some way to build nightly with the commit in place, akin to some form of `make nightly`?

**Comment by robiot** [comment]
@Shringe Hmm very strange, make sure to clone, run `git checkout fix/g_idle_add_once` then `make all`. Let me know if that worked.

**Comment by Shringe** [comment]
Yep, `make all` was it not `make release`, seems to work completely fine now.

**Comment by robiot** [comment]
Ok perfect! Thanks for testing it out!

**Pull request merged**
